
services:
  eureka-server:
    container_name: eureka-server-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - rede1
    environment:
      EUREKA_SERVER_URL: http://192.168.38.129:8761/eureka/

networks:
  rede1:
    external: true
