version: "3.8"

services:
  springboot:
    build:
      context: docker
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - app_network
    environment:
      EUREKA_SERVER_URL: http://192.168.38.129:8761/eureka/

networks:
  app_network:
    driver: bridge